### ISSUE TITLE
Replica bootstrap / rebootstrap fails if role writes to sync space

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#11039]
**Bug description**

Application role that writes to a synchronous space at startup fails to bootstrap in the election failover mode.

Tarantool version:

```
Tarantool 3.4.0-entrypoint-75-g714052225ebd
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/home/vlad/src/tarantool/tarantool/build/debug/install -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/vlad/src/tarantool/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0
```

**Steps to reproduce**

1. Download [test.zip](https://github.com/user-attachments/files/18490883/test.zip). It contains the configuration and code of the failing application role. See the appendix for more details.

2. Unzip the downloaded archive and enter the application directory.
   ```sh
   unzip test.zip && cd test
   ```

3. Run the application.
   ```sh
   tt stop -y && tt clean -f && tt start
   ```

4. Wait for a few seconds and check the status.
   ```sh
   tt status
   ```

**Actual behavior**

One instance fails to start:

```
$ tt status
 INSTANCE          STATUS       PID     MODE  CONFIG  BOX      UPSTREAM
 test:instance001  NOT RUNNING
 test:instance002  RUNNING      522949  RO    ready   running  disconnected
 test:instance003  RUNNING      522947  RW    ready   running  disconnected

The status of some instances requires attention.
Please rerun the command with the --details flag to see more information
```

The instance log contains `ER_SYNC_QUORUM_TIMEOUT` error:

```
$ tt log test:instance001
test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 replication.cc:563 I> assigned id 2 to replica 3d876a78-21bd-40ba-abc4-fffe25c11d01
test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 replication.cc:581 I> assigned name instance001 to replica 3d876a78-21bd-40ba-abc4-fffe25c11d01
test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 box.cc:2274 I> update replication_synchro_quorum = 2
test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 raft.c:637 I> RAFT: fencing paused
test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 applier.cc:1088 I> final data received
test:instance001: 2025-01-21 15:38:47.098 [522990] main/104/interactive box.cc:5407 E> failed to create a checkpoint
test:instance001: 2025-01-21 15:38:47.098 [522990] main/104/interactive txn_limbo.c:980 E> ER_SYNC_QUORUM_TIMEOUT: Quorum collection for a synchronous transaction is timed out
test:instance001: 2025-01-21 15:38:47.098 [522990] main/104/interactive box.cc:5987 F> can't initialize storage: Quorum collection for a synchronous transaction is timed out
test:instance001: Watchdog 2025/01/21 15:38:47 (WARN): "exit status 1".
test:instance001: Watchdog 2025/01/21 15:38:47 (INFO): the Instance has shutdown.
```

Note that the issue isn't 100% reproducible. If all instances start successfully, try doing step 3 again.

**Expected behavior**

All instances start successfully.

**Appendix**

The test application simulates the use case when the role wants to initialize some spaces right after the startup. To do that, it installs a `box.status` watcher, which creates a synchronous space and writes to it once the instance becomes writable. The loop between space creation and write is required to increase the probability of failure: it waits for a new instance to register in the cluster.

<details><summary>Application role code (test.lua)</summary>

```lua
local fiber = require('fiber')

local function test_apply()
    box.watch('box.status', function(_, value)
        if not value.is_ro then
            box.schema.space.create('test', {
                is_sync = true,
                if_not_exists = true,
            })
            box.space.test:create_index('primary', {
                if_not_exists = true,
            })
            while box.space._cluster:count() == 1 do
                fiber.yield()
            end
            box.space.test:replace({1})
        end
    end)
end

return {
    validate = function() end,
    apply = test_apply,
    stop = function() end,
}
```

</details>

<details><summary>Application config (config.yaml)</summary>

```yaml
credentials:
  users:
    replicator:
      password: 'topsecret'
      roles: [replication]
iproto:
  advertise:
    peer:
      login: replicator
replication:
  failover: election
roles:
- test
groups:
  group001:
    replicasets:
      replicaset001:
        instances:
          instance001:
            iproto:
              listen:
              - uri: '127.0.0.1:3301'
          instance002:
            iproto:
              listen:
              - uri: '127.0.0.1:3302'
          instance003:
            iproto:
              listen:
              - uri: '127.0.0.1:3303'
```

</details>

**Comment by sergepetrenko** [comment]
A workaround for both issues is to first start the replica as an anonymous one and only then register it in cluster. Basically such a way of replica registration doesn't require step 3 from the description above, and hence doesn't block.

Step 2 itself also has a minor problem: if final join stage is long enough and master needs the newly joined replica to gather quorum, it won't be able to do so until the replica receives all the final join rows.

**Comment by sergepetrenko** [comment]
Actually I don't see why we need the FINAL_JOIN / REGISTER stage. The replica might as well receive its registration during subscribe.

Yes, this will mean that a non-anonymous replica will create an initial snapshot without its own registration in _cluster, but does this really matter? Anonymous replicas are allowed to do this and I don't see why we should avoid this for normal replicas. Of course, it won't be able to write to global spaces, and will be anonymous (not due to config with `replication_anon = true` but due to the fact that it hasn't received its registration yet).

Pros: all problems of replica join to a synchronous cluster are solved:
1. no need to create a snapshot after cluster registration, and hence no blocking on waiting for synchronous transactions to confirm .
2. ability to start acking new synchronous transactions right after id is assigned (remember that there are no heartbeats/acks during final join/register stage).

Cons: I see none.

@Serpentian @Gerold103 what do you think?

**Comment by Gerold103** [comment]
Amazing analysis, thank you. Yes, I hate FINAL_JOIN. This step looks completely unnecessary, which became very clear when anon replicas were introduced.

I can think of only one downside - how would we handle restart after snap is created, but is still anon?

I firstly thought it would just work, but then I tried this:
```Lua
--
-- Instance 1
--
-- Step 1
--
box.cfg{
    listen = 3313,
}
box.schema.user.grant('guest', 'super')

--
-- Instance 2
--
-- Step 2
--
box.cfg{
    replication = {3313},
    read_only = true,
    replication_anon = true,
}
os.exit(0)
--
-- Step 3
--
box.cfg{
    replication = {3313},
    read_only = true,
    replication_anon = false,
}
```

It fails with just one log: `2025-01-24 19:08:04.705 [81566] main/104/interactive say.c:86 F> 'replication_anon' cfg didn't work`.

I would say, we should enable this behavior then. Apparently, we somehow don't support right now the anon-flag flip on the first `box.cfg` after restart.

It is also worth mentioning, that if FINAL_JOIN as a join-stage would be gone, it would have to stay in a simplified form above its current place, somewhere in `box_cfg_xc()`. Because the user code running on non-anon replicas might be relying on them being non-anon always. Hard to think of any specific real cases, but I could guess things related to `box.info.id` like logging, perhaps assertions that it is not 0.

Also such "temporary anon" replica must still allow synchro options like `election_mode = 'candidate'`. I guess, we would need quite a bit of work in `box_cfg_xc()` to allow all this when we see no anon flag in cfg, but see no ID in the snap.

Otherwise a very good and long awaited idea 💪!

**Comment by Serpentian** [comment]
> A workaround for both issues is to first start the replica as an anonymous one and register it in the cluster later, after it writes the initial snapshot. Basically such a way of replica registration doesn't require step 3 from the description above, and hence doesn't block.

Completely agree! We should finally get rid of the final join stage. We already discussed that several years ago (and I've written RFC for that) and this is one of the things, we should do to make reconfiguration of the sync replicaset safe:

![Image](https://github.com/user-attachments/assets/21ba08f6-b635-4a9a-bdf0-28d2a4d4e870)

**Comment by Serpentian** [comment]
> Actually I don't see why we need the FINAL_JOIN / REGISTER stage. 

So, `IPROTO_REGISTER` will be deprecated? In order to transfer from anon state of replication to the non-anon replica will just resubscribe? Basically for all replicas the joining procedure will look like that: `IPROTO_FETCH_SNAPSHOT` (fetching and creating initial state) -> `IPROTO_SUBSCRIBE` (registration of the replica if needed, and subsequent replication)?

I'm ok with such approach. the current one looks way too sophisticated without any good reason. But this way `IPROTO_SUBSCRIBE` will become a request of replica reconfiguration. But we already use that for GC consumers, if I'm not mistaken, so I don't mind. @Gerold103 was strongly against that.

**Comment by Gerold103** [comment]
Yes, this part I still don't like. I think `IPROTO_SUBSCRIBE` should be "read-only". How would it work in this case anyway? Right after `IPROTO_FETCH_SNAPSHOT` is complete, replica sends `IPROTO_SUBSCRIBE`? And it registers the replica? What about anon-replication? Would it have to stop current subscribe, change a flag in this request, and subscribe again? That looks like a crutch, really. Super ugly 🤮.

OTOH, when one has `IPROTO_REGISTER`, it could be sent inside the existing stream, without a reconnect. Or well, reconnect, but send `IPROTO_REGISTER` and then right afterwards `IPROTO_SUBSCRIBE`. I very much dislike bloating existing simple requests to start doing things they are not supposed to be doing. Why not remove `IPROTO_FETCH_SNAPSHOT` then? Just make a flag in `IPROTO_SUBSCRIBE` like "firstly send the snapshot". In the end we will end up with some `IPROTO_CTL` which would anyway internally be split into different types of requests to do.

TLDR: I don't think removal of `IPROTO_REGISTER` is needed to drop `IPROTO_FINAL_JOIN`.

**Comment by DifferentialOrange** [comment]
One place where it also happens is the `config_storage`: https://github.com/tarantool/tarantool-ee/blob/9382130d58d42309680c1d7f52f766166931a107/src/box/lua/config/storage/init.lua#L872

**Comment by sergepetrenko** [comment]
> Here's what can go wrong when replica join is performed in parallel with synchronous transaction load: During step 3 replica doesn't receive any new xlog rows, it stops receipt exactly at `stop_vclock`. And it may happen that `stop_vclock` lies in between some synchronous transaction and its confirmation, so the replica never receives the confirmation and hence cannot create a snapshot. This is exactly what happens in the report:
> 
> ```
> test:instance001: 2025-01-21 15:38:42.096 [522990] main/116/applier/replicator@127.0.0.1:3303 applier.cc:1088 I> final data received
> test:instance001: 2025-01-21 15:38:47.098 [522990] main/104/interactive box.cc:5407 E> failed to create a checkpoint
> test:instance001: 2025-01-21 15:38:47.098 [522990] main/104/interactive txn_limbo.c:980 E> ER_SYNC_QUORUM_TIMEOUT: Quorum collection for a synchronous transaction is timed out
> test:instance001: 2025-01-21 15:38:47.098 [522990] main/104/interactive box.cc:5987 F> can't initialize storage: Quorum collection for a synchronous transaction is timed out
> ```

This problem just happened on a real cluster on an attempt to rebootstrap a replica. Basically a replica may retry bootstrapping many times until finally `stop_vclock` happens to lie right after a synchronous transaction confirmation and before any new synchronous transactions.
