### ISSUE TITLE
Regression in 1.6.8-752-g8fc147c: client errors under load

### ISSUE THREAD

**Issue by kmansoft** [tarantool/tarantool#1649]
Following up on: https://groups.google.com/forum/#!topic/tarantool/j7f3l7xPqvA

Since the 1.6.8-752-g8fc147c update, I'm consistently seeing the errors below, in fact my load test fails almost 100% of the time:

> Error calling <function name here>: client timeout for request 27135

@kostja thinks it's related to this: https://github.com/tarantool/tarantool/commit/0d675fd5b59effb310bd96ef2154d426afc2ee0e and yes, it looks like the only change since the previous version (1.6.8-745-gb5173ac).

Test app and repro instructions:

https://github.com/kmansoft/tarantool_buffer_bug_752

**Comment by kostja** [comment]
Could you please help me start the go program? 
Here's what I get:
kostja@atlas ~/tarantool_buffer_bug_752
 % ./run_test_db_server.sh subs ping change
test_db_server.go:6:2: cannot find package "github.com/tarantool/go-tarantool" in any of:
	/usr/lib/go/src/pkg/github.com/tarantool/go-tarantool (from $GOROOT)
	($GOPATH not set)
push_db_util.go:7:2: cannot find package "gopkg.in/vmihailenco/msgpack.v2" in any of:
	/usr/lib/go/src/pkg/gopkg.in/vmihailenco/msgpack.v2 (from $GOROOT)
	($GOPATH not set)

**Comment by kostja** [comment]
Hi!
I was able to repeat the problem, and it seems that the root cause is go client sending too many queries to the server, without reading the response. Previously, we had a bug that the input buffer of the server could grow despite cfg.readahead setting, so very large batches could be sent without reading output. We fixed it in 1.6.8-745, so now the server simply stops accepting input until some output is read. 
The bug could be also caused by the Go driver for Tarantool, I will try to check it with the maintainer.

**Comment by kmansoft** [comment]
Yes, I use github.com/tarantool/go-tarantool which -- as far as I know -- is the *official* Go client library (?)

Yes, the test app is (partly) a benchmark, and yes, the rate at which it makes Tarantool requests is not limited by anything, it just goes as fast as it can.

I don't *think* there is any throttling in the Go client library...

... and IMHO it would be the wrong place to fix it (the client library can't possibly know if the server can accept more requests... unless you implement some sort of feedback loop, in every client driver for every language... complicating things...).

Can readahead be dynamic? So box.cfg would specify the maximum size, not initial?

Pinging @mialinx Go client maintainer.

**Comment by kostja** [comment]
@kmansoft , please let me stress one point: the deadlock happens not because the server stops reading, but because the *client* stops reading.

The flood protection algorithm has two cfg.readahead  buffers for input, which it reuses as soon as a request is processed and response sent to the client. If the client does not read server output, the buffer can not be reused. So the trouble is with the client which keeps sending queries, but doesn't read server responses.

**Comment by kmansoft** [comment]
The client stops reading -- but server does keep sending responses?

If that's the case, then it sounds more like a client bug.

And just want to note that I have tried setting the client side *timeout* to some ridiculously large value, and it did not help (it still failed, just took longer).

**Comment by kostja** [comment]
Yes, that is what I am observing in the debug get, there is data in out out
buffer but the client is not reading it (the socket is not available for
writing)

29 июля 2016 г. 10:22 PM пользователь "kmansoft" <notifications@github.com>
написал:

**Comment by kmansoft** [comment]
And another thing worth noting, in favor of a client library bug:

My test app uses synchronous Tarantool calls -- I mean it does *not* queue up a large number of requests only then waiting for them to complete.

And it's my understanding that every call to e.g. `dbconn.CallTyped` 1) sends a request to Tarantool and 2) waits for a response and 3) only then returns.

And so, there should be at most 20 (the number of worker threads) outstanding requests in and at most 20 outstanding responses.

**Comment by kostja** [comment]
* kmansoft <notifications@github.com> [16/07/30 00:05]:
> And another thing worth noting, in favor of a client library bug:
> 
> My test app uses synchronous Tarantool calls -- I mean it does *not* queue up a large number of requests only then waiting for them to complete.
> 
> And it's my understanding that every call to e.g. `dbconn.CallTyped` 1) sends a request to Tarantool and 2) waits for a response and 3) only then returns.
> 
> And so, there should be at most 20 (the number of worker threads) outstanding requests in and at most 20 outstanding responses.

Yep, you're right, there should be no more than 20 queries in
flight. Strangely enough, I can't repeat the problem with 1.7,
only  in 1.6. Will debug a bit more.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by kmansoft** [comment]
FWIW -

Last night I added debug printouts to go-tarantool's connection class, this is a "thread" that loops reading from a socket and decodes and dispatches server responses.

They are marked with "kman":

https://gist.github.com/kmansoft/ca57b24a8b7a7cfc014834f7c1558eb0#file-connection-go-L286

None of the "failure" or "interesting" printouts triggered before the failure occurred.

Interestingly, if I uncomment the "log.Printf kman tarantool decoded the header", slowing the reader down, then the issue is less likely to occur; it seems but I'm not entirely sure.

**Comment by kostja** [comment]
I believe the above patch fixes it, could you please checK?

**Comment by mialinx** [comment]
Here is stacktrace of **reader** goroutine at the moment just after getting an error.
Goroutine reads from the socket. So I guess problem is not in the client.

```
goroutine 21 [IO wait]:
net.runtime_pollWait(0x7fc94b172608, 0x72, 0xc8200b0000)
	/usr/lib/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82006a1b0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82006a1b0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82006a150, 0xc8200b0000, 0x20000, 0x20000, 0x0, 0x7fc94b16d028, 0xc8200700a0)
	/usr/lib/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820086030, 0xc8200b0000, 0x20000, 0x20000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc82006e240)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc82006e240, 0xc820260085, 0x5, 0x5, 0xc820036de8, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7fc94b172718, 0xc82006e240, 0xc820260085, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fc94b172718, 0xc82006e240, 0xc820260085, 0x5, 0x5, 0x419e17, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:315 +0x62
github.com/tarantool/go-tarantool.read(0x7fc94b172718, 0xc82006e240, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/nuf/go/src/github.com/tarantool/go-tarantool/connection.go:337 +0xc6
github.com/tarantool/go-tarantool.(*Connection).reader(0xc8200ac140)
	/home/nuf/go/src/github.com/tarantool/go-tarantool/connection.go:298 +0x121
created by github.com/tarantool/go-tarantool.Connect
	/home/nuf/go/src/github.com/tarantool/go-tarantool/connection.go:68 +0x346
```

**Comment by mialinx** [comment]
@kostja 
> I believe the above patch fixes it, could you please check? At least I can't repeat the hang any more.

Fix works for me.

**Comment by kmansoft** [comment]
Cool!

Looking at the change:

```
 -	return ibuf_used(&iobuf->in) == 0 && obuf_size(&iobuf->out) == 0;
 +	return ibuf_used(&iobuf->in) == 0 && obuf_used(&iobuf->out) == 0;
```

Since buffer sizes are presumably > 0, the expression was always false, and so `iobuf_is_idle` always returned `false`?

I will test as soon as it shows up in the Fedora repo.

Thank you for the quick fix!

**Comment by kmansoft** [comment]
Confirming fixed in 1.6.8-756-gd8d4ad0.

Tested on Ubuntu 16.04, regrettably there is no Fedora build(?)
